from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from deeplearning.preprocessing import ImageToArrayPreprocessor
from deeplearning.preprocessing import SimplePreprocessor
from deeplearning.datasets import SimpleDatasetLoader
from deeplearning.nn.conv import ShallowNet
from keras.optimizers import SGD
from